# programme qui permette d’encoder des valeurs dans une liste
print( 'entrer un nombre :')
a = float( input( ))
print( 'entrer un nombre :')
b = float( input( ))
print( 'entrer un nombre :')
c = float( input( ))
print( 'entrer un nombre :')
d= float( input( ))
print( 'entrer un nombre :')
u = float( input( ))
t = [ ]
t.append(a)
t.append(b)
t.append(c)
t.append(d)
t.append(u)
print( t )